### ISSUE TITLE
ERROR: Unexpected cycle shape. Will only retain first frame group

### ISSUE THREAD

**Issue by ht-lau** [MannLabs/alphadia#225]
Hi, 

I ran into the error, unexpected cycle shape.  I wonder if it is because of my instrument method.  My instrument is the TimsTOF pro2, and the following is the diaPASEF cycle.  Note that there is an extra MS1 cycle. 

#MS Type,Cycle Id,Start IM [1/K0],End IM [1/K0],Start Mass [m/z],End Mass [m/z],CE [eV]
MS1,0,-,-,-,-,-
MS1,6,-,-,-,-,-
PASEF,1,0.6,0.88,250,445.54647,-
PASEF,2,0.6,0.905,444.54647,495.256462,-
PASEF,3,0.6,0.925,494.256462,529.802078,-
PASEF,4,0.6,0.945,528.802078,559.286462,-
PASEF,5,0.6,0.965,558.286462,584.80554,-
PASEF,7,0.6,0.99,583.80554,609.82119,-
PASEF,8,0.6,1.01,608.82119,634.338758,-
PASEF,9,0.6,1.04,633.338758,659.809144,-
PASEF,10,0.6,1.06,658.809144,684.637416,-
PASEF,11,0.6,1.12,683.637416,710.29279,-
PASEF,1,0.88,1.6,709.29279,736.406824,-
PASEF,2,0.905,1.6,735.406824,764.869666,-
PASEF,3,0.925,1.6,763.869666,794.428074,-
PASEF,4,0.945,1.6,793.428074,826.857108,-
PASEF,5,0.965,1.6,825.857108,862.89685,-
PASEF,7,0.99,1.6,861.89685,904.9257,-
PASEF,8,1.01,1.6,903.9257,956.563184,-
PASEF,9,1.04,1.6,955.563184,1025.994042,-
PASEF,10,1.06,1.6,1024.994042,1128.06233,-
PASEF,11,1.12,1.6,1127.06233,1800,-

Following is part of the log (v1.6.2, GUI) 
==================================================
0:03:56.267669 PROGRESS: Starting Search Workflows
0:03:56.267669 PROGRESS: Loading raw file 1/14: 20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316
0:03:56.267669 INFO: Creating parent folder for workflows at E:\MSdata\20240423_prmInter7_rep4_intra_2columns\out_alphaDIA\.progress
0:03:56.267669 INFO: Creating workflow folder for 20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316 at E:\MSdata\20240423_prmInter7_rep4_intra_2columns\out_alphaDIA\.progress\20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316
0:03:56.267669 INFO: Importing data from E:\MSdata\20240423_prmInter7_rep4_intra_2columns\raw_DIA\20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316.d
0:03:56.267669 INFO: Using .d import for E:\MSdata\20240423_prmInter7_rep4_intra_2columns\raw_DIA\20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316.d
0:03:56.267669 INFO: Reading frame metadata for E:\MSdata\20240423_prmInter7_rep4_intra_2columns\raw_DIA\20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316.d
0:03:57.325609 INFO: Reading 19,710 frames with 1,221,717,704 detector events for E:\MSdata\20240423_prmInter7_rep4_intra_2columns\raw_DIA\20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316.d

  0%|          | 0/19710 [00:00<?, ?it/s]
  0%|          | 1/19710 [00:01<6:26:50,  1.18s/it]
  1%|          | 130/19710 [00:01<02:19, 140.27it/s]
  3%|2         | 574/19710 [00:01<00:26, 715.62it/s]
  6%|5         | 1102/19710 [00:01<00:12, 1446.41it/s]
  8%|8         | 1631/19710 [00:01<00:08, 2161.50it/s]
 11%|#1        | 2212/19710 [00:01<00:06, 2856.71it/s]
 14%|#3        | 2664/19710 [00:01<00:06, 2651.39it/s]
 15%|#5        | 3044/19710 [00:02<00:09, 1810.63it/s]
 17%|#6        | 3334/19710 [00:02<00:10, 1573.20it/s]
 18%|#8        | 3568/19710 [00:02<00:10, 1547.83it/s]
 19%|#9        | 3775/19710 [00:02<00:10, 1537.38it/s]
 20%|##        | 3965/19710 [00:02<00:10, 1492.79it/s]
 21%|##        | 4138/19710 [00:03<00:10, 1464.65it/s]
 22%|##1       | 4300/19710 [00:03<00:10, 1443.73it/s]
 23%|##2       | 4455/19710 [00:03<00:10, 1466.31it/s]
 23%|##3       | 4610/19710 [00:03<00:10, 1447.76it/s]
 24%|##4       | 4761/19710 [00:03<00:10, 1387.16it/s]
 25%|##4       | 4904/19710 [0:04:14.975387 INFO: Indexing E:\MSdata\20240423_prmInter7_rep4_intra_2columns\raw_DIA\20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316.d...
0:04:15.225177 INFO: Opening handle for E:\MSdata\20240423_prmInter7_rep4_intra_2columns\raw_DIA\20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316.d
0:04:15.241385 INFO: Fetching mobility values from E:\MSdata\20240423_prmInter7_rep4_intra_2columns\raw_DIA\20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316.d
0:04:15.241385 INFO: Closing handle for E:\MSdata\20240423_prmInter7_rep4_intra_2columns\raw_DIA\20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316.d
0:04:15.241385 INFO: Opening handle for E:\MSdata\20240423_prmInter7_rep4_intra_2columns\raw_DIA\20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316.d
0:04:15.281232 INFO: Fetching mz values from E:\MSdata\20240423_prmInter7_rep4_intra_2columns\raw_DIA\20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316.d
0:04:15.298119 INFO: Closing handle for E:\MSdata\20240423_prmInter7_rep4_intra_2columns\raw_DIA\20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316.d
0:04:15.302325 INFO: Indexing quadrupole dimension
0:04:15.868764 ERROR: Unexpected cycle shape. Will only retain first frame group
0:04:15.869275 ERROR: Search for 20240423_prmInter7_rep4_intra_0d5load_150ng_1_1_5316 failed with error Unexpected cycle shape. Will only retain first frame group
Traceback (most recent call last):
  File "alphadia\planning.py", line 313, in run
    workflow.load(dia_path, speclib)
  File "alphadia\workflow\peptidecentric.py", line 122, in load
    super().load(
  File "alphadia\workflow\base.py", line 80, in load
    self._dia_data = self._get_dia_data_object(dia_data_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "alphadia\workflow\base.py", line 181, in _get_dia_data_object
    dia_data = bruker.TimsTOFTranspose(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "alphadia\data\bruker.py", line 70, in __init__
    raise ValueError(
ValueError: Unexpected cycle shape. Will only retain first frame group
0:04:15.873912 INFO: Traceback (most recent call last):
  File "alphadia\cli.py", line 341, in run
    plan.run()
  File "alphadia\planning.py", line 358, in run
    raise e
  File "alphadia\planning.py", line 313, in run
    workflow.load(dia_path, speclib)
  File "alphadia\workflow\peptidecentric.py", line 122, in load
    super().load(
  File "alphadia\workflow\base.py", line 80, in load
    self._dia_data = self._get_dia_data_object(dia_data_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "alphadia\workflow\base.py", line 181, in _get_dia_data_object
    dia_data = bruker.TimsTOFTranspose(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "alphadia\data\bruker.py", line 70, in __init__
    raise ValueError(
ValueError: Unexpected cycle shape. Will only retain first frame group

0:04:15.873912 ERROR: Unexpected cycle shape. Will only retain first frame group
==============================================

Thank you in advance,
HT

**Comment by GeorgWa** [comment]
Hi, we haven't processed diaPASEF data with repeated scans yet. Do you have a file and a small, matching library you can share?

**Comment by GeorgWa** [comment]
This would be great! I also have a library for hela.

**Comment by ht-lau** [comment]
George, is there a place that I can upload it? Thanks

**Comment by GeorgWa** [comment]
Thanks! You should be able to upload it here:
https://datashare.biochem.mpg.de/s/UFCrZBADX9JB22l

**Comment by ht-lau** [comment]
Uploaded. Thanks
