### ISSUE TITLE
ERROR: Failed to determine start of DIA cycle.

### ISSUE THREAD

**Issue by nbacalzo507** [MannLabs/alphadia#247]
Hi,

I'm trying out AlphaDIA for the first time and I encountered this error message (see below). My files are from QExactive ran in staggered windows DIA acquisition. I'm wondering if the staggered window caused this error. 

`  File "alphadia\data\alpharaw.py", line 359, in __init__
    self.process_alpharaw(**kwargs)
  File "alphadia\data\alpharaw.py", line 277, in process_alpharaw
    self.cycle, self.cycle_start, self.cycle_length = determine_dia_cycle(
                                                      ^^^^^^^^^^^^^^^^^^^^
  File "alphadia\data\alpharaw.py", line 194, in determine_dia_cycle
    raise ValueError("Failed to determine start of DIA cycle.")
ValueError: Failed to determine start of DIA cycle.
0:13:46.788233 INFO: Traceback (most recent call last):
  File "alphadia\data\alpharaw.py", line 268, in process_alpharaw
    self.cycle, self.cycle_start, self.cycle_length = determine_dia_cycle(
                                                      ^^^^^^^^^^^^^^^^^^^^
  File "alphadia\data\alpharaw.py", line 194, in determine_dia_cycle
    raise ValueError("Failed to determine start of DIA cycle.")
ValueError: Failed to determine start of DIA cycle.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "alphadia\cli.py", line 343, in run
    plan.run()
  File "alphadia\planning.py", line 363, in run
    raise e
  File "alphadia\planning.py", line 318, in run
    workflow.load(dia_path, speclib)
  File "alphadia\workflow\peptidecentric.py", line 122, in load
    super().load(
  File "alphadia\workflow\base.py", line 80, in load
    self._dia_data = self._get_dia_data_object(dia_data_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "alphadia\workflow\base.py", line 201, in _get_dia_data_object
    dia_data = alpharaw.Thermo(
               ^^^^^^^^^^^^^^^^
  File "alphadia\data\alpharaw.py", line 359, in __init__
    self.process_alpharaw(**kwargs)
  File "alphadia\data\alpharaw.py", line 277, in process_alpharaw
    self.cycle, self.cycle_start, self.cycle_length = determine_dia_cycle(
                                                      ^^^^^^^^^^^^^^^^^^^^
  File "alphadia\data\alpharaw.py", line 194, in determine_dia_cycle
    raise ValueError("Failed to determine start of DIA cycle.")
ValueError: Failed to determine start of DIA cycle.

0:13:46.788233 ERROR: Failed to determine start of DIA cycle.`

**Comment by GeorgWa** [comment]
Hi, we haven't yet processed staggered window DIA data, yet this should be possible.
Can you share a raw file (some qc hela) with the acquisition method and upload it here: https://datashare.biochem.mpg.de/s/UFCrZBADX9JB22l

Best,
Georg

**Comment by tobiasko** [comment]
A suggestion: This article describes a benchmark data set for different DIA flavours on different instruments:

Van Puyvelde, B., Daled, S., Willems, S. et al. A comprehensive LFQ benchmark dataset on modern day acquisition strategies in proteomics. Sci Data 9, 126 (2022). https://doi.org/10.1038/s41597-022-01216-6

The DIA data from the qOrbitrap (AIF) is also staggered.

Best,
Tobi

**Comment by GeorgWa** [comment]
Hi, thanks for the ressource! 
From the method table in the supplement I can't see any issue. We have processed a lot similar data. My guess is there is some overlap or there are repeated windows where the cycle determination fails.

Unfortunately Thermo raw files have no notion of a DIA cycle but knowing it greatly accelerates computation.

**Comment by nbacalzo507** [comment]
Unfortunately, I don't have HeLa injections with me. I'll double-check my acquisition method and play around with the demultiplexing too. thanks!

**Comment by jabrelab** [comment]
Thanks Magnus! 

I added two raw files here: 
https://drive.google.com/drive/folders/1sEQCxJ-_aEQSsjMTeuUYV1-x2E0JTizX?usp=sharing

**Comment by wenbostar** [comment]
I got a similar error when using the latest AlphaDIA (version 2.1.1) to analyze a staggered DIA dataset (mzML format, it has been demultiplexed using msconvert):

```
0:10:40.720176 ERROR: Please check if this is a valid DIA data set.

    1. This could be DDA data?
    2. Is it DIA data where the order of windows is not the same in each cycle?
    3. Might be due to DIA data where the cycle does not start at beginning of file but e.g. only after a series of blank scans.

    AlphaDIA has a strict definition of DIA cycles: same order of scans within a cycle and the cycle must appear throughout the whole file without gaps.
    
0:10:40.720217 ERROR: NOT_VALID_DIA_DATA: Not valid DIA data.
Failed to determine start of DIA cycle.
Please check if this is a valid DIA data set.

    1. This could be DDA data?
    2. Is it DIA data where the order of windows is not the same in each cycle?
    3. Might be due to DIA data where the cycle does not start at beginning of file but e.g. only after a series of blank scans.

    AlphaDIA has a strict definition of DIA cycles: same order of scans within a cycle and the cycle must appear throughout the whole file without gaps.

```

**Comment by mschwoer** [comment]
Hey @wenbostar ,

could you provide one of your input files and the `frozen_config.yaml` ?

best,
Magnus
